### ISSUE TITLE
Errors in configuration file

### ISSUE THREAD

**Issue by mehmet-27** [crowdin/android-studio-plugin#129]
**Describe the bug**
Even though I wrote the translation and source values ​​as required in the config file, I get the error that they could not be found.

my config file like that(file name crowdin.yml):

```
files:
  - source: '/api/src/main/resources/locales/en_US.yml'
  - translation: '/api/src/main/resources/locales/%locale_with_underscore%.%file_extension%'
project_id: '1111'
api_token: 'xxxx'
```
error image
![image](https://github.com/crowdin/android-studio-plugin/assets/84019475/1415e121-6d7a-408a-95d4-126668e4ae7b)

**Comment by andrii-bodnar** [comment]
Try the following configuration:

```yml
files:
  - source: '/api/src/main/resources/locales/en_US.yml'
    translation: '/api/src/main/resources/locales/%locale_with_underscore%.%file_extension%'
project_id: '1111'
api_token: 'xxxx'
```

Also, make sure you are using the latest version of the plugin.
